'use client';
import { useState } from 'react';
import { Activity, ArrowUpRight, Bell, Bot, ChevronDown, CloudSun, Droplets, Leaf, Mic, MoreHorizontal, Search, Send, ShieldCheck, Sparkles, Sprout, Sun, TrendingUp, Waves, Wind } from 'lucide-react';

const agents = [{name:'Weather intelligence', icon:CloudSun, state:'Live', color:'cyan'}, {name:'Crop doctor', icon:Leaf, state:'Ready', color:'lime'}, {name:'Market pulse', icon:TrendingUp, state:'Synced', color:'violet'}];
const nav = ['Overview','AI Krushi Mitra','My fields','Market intelligence','Advisories'];

export default function Home() {
 const [active, setActive] = useState('Overview'); const [query, setQuery] = useState(''); const [sent, setSent] = useState(false);
 const ask = () => { if (!query.trim()) return; setSent(true); setTimeout(()=>setSent(false), 2800); setQuery(''); };
 return <main className="shell">
  <aside className="sidebar"><div className="brand"><div className="brand-mark"><Sprout size={22}/></div><div><b>Krushi<span>Verse</span></b><small>AI AGRICULTURE OS</small></div></div>
   <div className="farm-switch"><div className="avatar">RK</div><div><strong>Ramesh&apos;s farm</strong><small>Baramati · 8.5 acres</small></div><ChevronDown size={15}/></div>
   <nav>{nav.map((item,i)=><button className={active===item?'active':''} onClick={()=>setActive(item)} key={item}>{[Activity,Bot,Leaf,TrendingUp,ShieldCheck][i]({size:18,strokeWidth:1.8})}<span>{item}</span>{item==='AI Krushi Mitra'&&<em>AI</em>}</button>)}</nav>
   <div className="sidebar-bottom"><div className="pro-card"><Sparkles size={17}/><b>Pro intelligence</b><p>Deep farm insights are on.</p><a>Explore insights <ArrowUpRight size={13}/></a></div><div className="profile"><div className="avatar orange">RK</div><div><strong>Ramesh Kumar</strong><small>Farmer account</small></div><MoreHorizontal size={18}/></div></div>
  </aside>
  <section className="content"><header><div className="crumb">KRUSHIVERSE <span>/</span> {active.toUpperCase()}</div><div className="header-actions"><div className="search"><Search size={16}/><input placeholder="Search your farm..."/><kbd>⌘ K</kbd></div><button className="icon-btn"><Bell size={18}/><i/></button><div className="date">18 JUL 2026 <span>·</span> SATURDAY</div></div></header>
   <div className="hero"><div><div className="eyebrow"><span className="pulse"/> AI KRUSHI MITRA <span className="tag">ONLINE</span></div><h1>Good morning,<br/><i>Ramesh.</i></h1><p>Your farm is looking strong today. Here&apos;s what your intelligence layer sees.</p></div><div className="hero-orb"><div className="orb-ring r1"/><div className="orb-ring r2"/><Sun size={34}/><span>28°</span><small>BAR AMATI</small></div></div>
   <div className="stats"><Stat label="Field health" value="86" unit="%" trend="+4.2%" icon={Leaf} color="lime"/><Stat label="Soil moisture" value="63" unit="%" trend="Optimal" icon={Droplets} color="cyan"/><Stat label="Market outlook" value="₹7,240" unit="/ q" trend="+8.6%" icon={TrendingUp} color="violet"/><Stat label="Weather risk" value="Low" unit="" trend="Next 72h" icon={ShieldCheck} color="orange"/></div>
   <div className="grid"><div className="panel mitra"><div className="panel-head"><div><div className="eyebrow">YOUR INTELLIGENCE LAYER</div><h2>Ask Mitra anything.</h2></div><div className="live-dot">● LIVE</div></div><div className="chat"><div className="mitra-avatar"><Bot size={20}/></div><div><b>Namaste, Ramesh <span>✦</span></b><p>I&apos;m monitoring your cotton fields, weather and mandi prices. What would you like to know?</p></div></div><div className="prompt-box"><textarea value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&(e.preventDefault(),ask())} placeholder="Ask in Marathi, Hindi or English..."/><div className="prompt-foot"><button className="mic"><Mic size={17}/></button><small>Press <kbd>Enter</kbd> to ask</small><button className="send" onClick={ask}>{sent?<ShieldCheck size={18}/>:<Send size={18}/>}</button></div></div>{sent&&<div className="toast">Mitra is thinking · connecting to your farm graph...</div>}<div className="suggestions"><span>Try asking</span><button onClick={()=>setQuery('Should I irrigate my cotton today?')}>Irrigation advice <ArrowUpRight size={13}/></button><button onClick={()=>setQuery('What is today’s cotton mandi price?')}>Mandi prices <ArrowUpRight size={13}/></button></div></div>
    <div className="panel climate"><div className="panel-head"><div><div className="eyebrow">MICROCLIMATE</div><h2>Today&apos;s conditions</h2></div><button className="dots">•••</button></div><div className="weather-main"><CloudSun size={32}/><div><strong>28°</strong><span>Partly cloudy</span></div><small>Feels like 30°</small></div><div className="weather-bars"><Weather label="Humidity" value="68%" icon={Droplets}/><Weather label="Wind" value="12 km/h" icon={Wind}/><Weather label="Rain chance" value="24%" icon={Waves}/></div><div className="forecast"><span>Next 72 hours</span><b>Low risk <ShieldCheck size={14}/></b></div></div></div>
   <div className="section-row"><div><div className="eyebrow">AUTONOMOUS AGENTS</div><h2>Systems working for you <span>↗</span></h2></div><button className="view">View all agents <ArrowUpRight size={15}/></button></div><div className="agent-grid">{agents.map(({name,icon:Icon,state,color})=><div className="agent" key={name}><div className={'agent-icon '+color}><Icon size={19}/></div><div><b>{name}</b><small><span className="tiny-pulse"/> {state}</small></div><ArrowUpRight className="agent-arrow" size={17}/></div>)}</div>
  </section>
 </main>
}
function Stat({label,value,unit,trend,icon:Icon,color}:{label:string,value:string,unit:string,trend:string,icon:any,color:string}){return <div className="stat"><div className={'stat-icon '+color}><Icon size={18}/></div><small>{label}</small><div className="stat-value">{value}<sup>{unit}</sup></div><span className="trend">↗ {trend}</span></div>}
function Weather({label,value,icon:Icon}:{label:string,value:string,icon:any}){return <div className="weather-item"><Icon size={15}/><span>{label}</span><b>{value}</b></div>}
